version: '3'

tasks:
  default:
    desc: list all tasks
    cmds:
    - task --list --sort none
  init:
    desc: install pre-commit and npm dependencies
    cmds:
    - uv run pre-commit install
    - uv run pre-commit autoupdate
    - npm install
    - npm run prepare
  commit:
    desc: commit
    aliases: [c]
    cmds:
    - npm run commit

  ruff:
    desc: run ruff linter
    cmds:
    - uv run ruff check python/src
    - uv run ruff format python/src
